server:
  port: 3634

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      routes:
        - id: elastic_search
          uri: http://10.148.0.2:2160
          predicates:
            - Path=/api/location/search
            - Method=GET
            - Query=name

        - id: elastic_search_all
          uri: http://10.148.0.2:2160
          predicates:
            - Path=/api/location/
            - Method=GET

        - id: spring_register
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/signup
            - Method=POST

        - id: spring_login
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/login
            - Method=POST

        - id: change_password
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/changepassword/{id}
            - Method=PATCH
          filters:
            - AddRequestParameter=id, {id}

        - id: search_hotels
          uri: http://10.148.0.2:9089
          predicates:
            - Path=/api/hotel/search
            - Method=POST

        - id: user_services
          uri: http://10.148.0.2:2010
          predicates:
            - Path=/user/getuser
            - Method=GET
            - Query=userid

        - id: update_user
          uri: http://10.148.0.2:2010
          predicates:
            - Path=/user/updateuser/{userid}
            - Method=PUT
          filters:
            - AddRequestParameter=userid, {userid}

        - id: room_detail_get
          uri: http://10.148.0.2:49912
          predicates:
            - Path=/api/room/detail/get-room
            - Method=GET
            - Query=roomId

        - id: rooms_list
          uri: http://10.148.0.2:49912
          predicates:
            - Path=/api/room/list/{hotelId}
            - Method=GET
          filters:
            - AddRequestParameter=id, {hotelId}

  main:
    web-application-type: reactive