server:
  port: 3634

spring:

  ## Configuration Gateway
  cloud:
    gateway:
      routes:
        - id: elastic_search
          uri: http://35.187.252.114:2160
          predicates:
            - Path=/api/search/{name}
            - Method=GET
          filters:
            - AddRequestParameter=name, {name}

        - id: spring_register
          uri: http://35.187.252.114:1234
          predicates:
            - Path=/user/signup
            - Method=POST

        - id: spring_login
          uri: http://35.187.252.114:1234
          predicates:
            - Path=/user/login
            - Method=POST

  main:
    web-application-type: reactive