server:
  port: 3634

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      routes:
        - id: elastic_search
          uri: http://10.148.0.2:2160
          predicates:
            - Path=/api/search/{name}
            - Method=GET
          filters:
            - AddRequestParameter=name, {name}

        - id: spring_register
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/user/signup
            - Method=POST

        - id: spring_login
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/user/login
            - Method=POST

        - id: search_hotels
          uri: http://10.148.0.2:9089
          predicates:
            - Path=/api/hotel/search
            - Method=POST
          
  main:
    web-application-type: reactive