server:
  port: 3634

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      routes:
          # Search API
        - id: elastic_search
          uri: http://10.148.0.2:2160
          predicates:
            - Path=/api/location/search
            - Method=GET
            - Query=name

        - id: search_hotels
          uri: http://10.148.0.2:9089
          predicates:
            - Path=/api/hotel/search
            - Method=POST

        # Login API
        - id: spring_register
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/signup
            - Method=POST

        - id: spring_login
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/login
            - Method=POST

        - id: change_password
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/changepassword/{id}
            - Method=PATCH
          filters:
            - AddRequestParameter=id, {id}

        - id: forgot_password
          uri: http://10.148.0.2:1234
          predicates:
            - Path=/auth/forgetpassword
            - Method=POST

          # Users API
        - id: user_services
          uri: http://10.148.0.2:2010
          predicates:
            - Path=/user/getuser
            - Method=GET
            - Query=userid

        - id: update_user
          uri: http://10.148.0.2:2010
          predicates:
            - Path=/user/updateuser
            - Method=PUT
            - Query=userid

        - id: update_image
          uri: http://10.148.0.2:2010
          predicates:
            - Path=/user/updateimage
            - Method=POST
            - Query=userid

          # Rooms API
        - id: room_detail_get
          uri: http://10.148.0.2:49912
          predicates:
            - Path=/api/room/detail/get-room
            - Method=GET
            - Query=roomId

        - id: rooms_list
          uri: http://10.148.0.2:49912
          predicates:
            - Path=/api/room/list
            - Method=GET
            - Query=hotelId

          # Hotels API
        - id: hotel_detail
          uri: http://10.148.0.2:45397
          predicates:
            - Path=/api/hotel/detail
            - Method=GET
            - Query=hotelId

        - id: add_hotel
          uri: http://10.148.0.2:45397
          predicates:
            - Path=/api/hotel/add
            - Method=POST

        - id: delete_hotel
          uri: http://10.148.0.2:45397
          predicates:
            - Path=/api/hotel/delete
            - Method=DELETE
            - Query=hotelId

        - id: suggest_hotel
          uri: http://10.148.0.2:45397
          predicates:
            - Path=/api/hotel/suggestHotel
            - Method=GET
        # Facilities API
        - id: facility_list
          uri: http://10.148.0.2:7128
          predicates:
            - Path=/api/facility/list-all
            - Method=GET

        # Booking & Bank API
        - id: booking
          uri: http://10.148.0.2:8082
          predicates:
            - Path=/booking/pushlish
            - Method=POST

        - id: list_bank_userId
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/getlistaccount
            - Query=userid

        - id: get_banking
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/getbank
            - Method=GET
            - Query=banktype

        - id: add_bank_card
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/addnewbank
            - Method=POST
            - Query=userid

        - id: get_after_booking
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/get-orders
            - Method=GET

        - id: get_ticket
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/getTicket
            - Method=GET

        - id: cancel_booking
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/cancelBooking
            - Method=PUT
            - Query=bookingId

        - id: get_otp
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/otp/{id}
            - Method=GET
          filters:
            - AddRequestParameter=id, {id}

        - id: post_otp
          uri: http://10.148.0.2:1947
          predicates:
            - Path=/booking/otp/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

        # Help Service
        - id: help_service
          uri: http://10.148.0.2:56273
          predicates:
            - Path=/api/help/sendHelp
            - Method=POST

        # Chat Service
        - id: chat_service
          uri: http://10.148.0.2:8877
          predicates:
            - Path=/sendChat
            - Method=POST

        - id: get_chatList
          uri: http://10.148.0.2:8877
          predicates:
            - Path=/getChat
            - Method=GET

        # Rating Service
        - id: post_rating
          uri: http://10.148.0.2:57503
          predicates:
            - Path=/api/rating
            - Method=POST

        - id: list_rating
          uri: http://10.148.0.2:57503
          predicates:
            - Path=/api/list-rating
            - Method=GET
            - Query=hotelId

  main:
    web-application-type: reactive
